name: playhouse
description: Grey & Ivy Prototype

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.56.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_svg/
  flutter_svg: ^0.22.0

  # https://pub.dartlang.org/packages/uuid
  uuid: ^3.0.0

  # https://pub.dev/packages/image/
  image: ^3.0.0

  # https://pub.dev/packages/flutter_sound/
  flutter_sound: ^8.0.0

  # https://pub.dev/packages/flutter_inappwebview/
  # https://inappwebview.dev/docs/
  flutter_inappwebview: ^5.0.0

  # https://pub.dev/packages/font_awesome_flutter/
  font_awesome_flutter: ^9.0.0

##  # https://pub.dev/packages/flutter_unity_widget/
##  flutter_unity_widget: ^4.0.0

  # https://pub.dev/packages/crop/
  crop: ^0.5.0

#  # https://pub.dev/packages/image_cropper
#  image_cropper: ^1.0.0

  # https://pub.dev/packages/mvc_application/
  mvc_application: ^7.0.0
#    path: ../../packages/mvc_application

# https://pub.dev/packages/firebase_crashlytics/
  firebase_crashlytics: ^2.0.0

# https://pub.dev/packages/firebase_auth/
#  firebase_auth: ^1.0.0
#  flutter_signin_button: ^2.0.0
#  google_sign_in: ^5.0.0

# https://pub.dev/packages/dbutils
  dbutils: ^3.0.0
#    path: ../../packages/dbutils

# https://pub.dev/packages/auto_size_text/
  auto_size_text: ^2.0.0

# https://pub.dev/packages/cached_network_image/
#  cached_network_image: ^3.0.0

## https://pub.dev/packages/scrollytell
#  scrollytell: ^1.0.0
#
## https://pub.dev/packages/photo_gallery
#  photo_gallery: ^0.4.0

#  transparent_image: ^2.0.0

#  permission_handler: ^6.0.0

#  video_player: ^2.0.0

#
#  dio: ^2.0.0

# https://pub.dev/packages/google_fonts/
  google_fonts: ^2.0.0

#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.0

  # https://pub.dev/packages/remote_config
#  remote_config: ^1.0.0

# https://pub.dev/packages/image_picker/
#  image_picker: ^0.8.0

# https://pub.dev/packages/images_picker/
  images_picker: ^1.0.0

  # https://pub.flutter-io.cn/packages/image_size_getter/
#  image_size_getter: ^1.0.0

  # https://pub.dev/packages/state_set/
  state_set: # ^3.0.0
    path: ../../packages/state_set

  # https://pub.dev/packages/page_view_indicators
  page_view_indicators: ^2.0.0

  # https://pub.dev/packages/percent_indicator
  percent_indicator: ^3.0.0

  # https://pub.dev/packages/permission_handler/
  permission_handler: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/pedantic
  pedantic: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/
     - assets/i10n/i10n.csv

     - assets/images/submodules/river_bend02.jpg

     - assets/images/submodules/lock.png
     - assets/images/submodules/spirit_of_place02.jpg

     - assets/images/submodules/Build_Final Budget_Exterior Design 01.jpg
     - assets/images/submodules/Build_Final Budget_Exterior Design 02.jpg
     - assets/images/submodules/Build_Final Budget_Exterior Design 03.jpg
     - assets/images/submodules/Build_Final Budget_Exterior Design 04.jpg
     - assets/images/submodules/Build_Final Budget_Interior Design 01.jpg
     - assets/images/submodules/Build_Final Budget_Interior Design 02.jpg
     - assets/images/submodules/Build_Final Budget_Interior Design 03.jpg
     - assets/images/submodules/Build_Final Budget_Interior Design 04.jpg
     - assets/images/submodules/Build_Final Budget_Landscape Design 01.jpg
     - assets/images/submodules/Build_Final Budget_Landscape Design 02.jpg
     - assets/images/submodules/Build_Final Budget_Landscape Design 03.jpg
     - assets/images/submodules/Build_Final Budget_Landscape Design 04.jpg

     - assets/images/submodules/Design_Conceptual Sketching_ Preliminary Sketch 01.jpg
     - assets/images/submodules/Design_Conceptual Sketching_ Preliminary Sketch 02.jpg
     - assets/images/submodules/Design_Conceptual Sketching_Bubble Diagram 01.jpg
     - assets/images/submodules/Design_Conceptual Sketching_Bubble Diagram 02.jpg
     - assets/images/submodules/Design_Conceptual Sketching_Sun, Light, Wind _ Sound 01.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Elevation 01.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Elevation 02.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Elevation 03.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Elevation 04.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Plan 01.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Plan 02.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Plan 03.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Plan 04.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Section 01.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Section 02.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Section 03.jpg
     - assets/images/submodules/Design_Plan, Section _ Elevation_Section 04.jpg

     - assets/images/submodules/Discover_Drawing _ Drafting_Advanced Techniques 01.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Advanced Techniques 02.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Intro to Drawing 01.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Intro to Drawing 02.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Intro to SketchUp 01.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Intro to SketchUp 02.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Intro to SketchUp 03.jpg
     - assets/images/submodules/Discover_Drawing _ Drafting_Intro to SketchUp 04.jpg
     - assets/images/submodules/Discover_Site Selection_Soil, Slope _ Drainage 01.jpg
     - assets/images/submodules/Discover_Site Selection_Soil, Slope _ Drainage 02.jpg
     - assets/images/submodules/Discover_Site Selection_Spirit of Place 01.jpg
     - assets/images/submodules/Discover_Site Selection_Spirit of Place 02.jpg
     - assets/images/submodules/Discover_Site Selection_Spirit of Place 03.jpg
     - assets/images/submodules/Discover_Site Selection_Sun 01.jpg
     - assets/images/submodules/Discover_Site Selection_Sun 02.jpg
     - assets/images/submodules/Discover_Site Selection_Wind _ Weather 01.jpg
     - assets/images/submodules/Discover_Site Selection_Wind _ Weather 02.jpg

     - assets/images/river_bend02.jpg
     - assets/images/construction_site02.jpg
     - assets/images/warehouse02.jpg
     - assets/images/city_night02.jpg
     - assets/images/church_garbagetruck02.jpg
     - assets/images/riverbrook_pinktree02.jpg
     - assets/images/street_intersection02.jpg
     - assets/images/desert_housing02.jpg
     - assets/images/winter_cabin02.jpg
     - assets/images/city_park02.jpg
     - assets/images/country_trail02.jpg
     - assets/images/country_waterfall02.jpg

     - assets/images/tasks/info.jpg
     - assets/images/tasks/check_mark.jpg

     - assets/images/tasks/search_image.jpg
     - assets/images/tasks/search_internet.jpg

     - assets/images/tasks/abc02.jpg
     - assets/images/tasks/AR02.jpg
     - assets/images/tasks/movieCamera02.jpg
     - assets/images/tasks/pencil02.jpg
     - assets/images/tasks/picture02.jpg
     - assets/images/tasks/questionMark02.jpg

     - assets/google_fonts/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/google_fonts/Cabin-Regular.ttf
        - asset: assets/google_fonts/Cabin-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/google_fonts/Ubuntu-Regular.ttf
        - asset: assets/google_fonts/Ubuntu-Medium.ttf
# Add custom icons
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/ReminderIcon.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
