name: playhouse
description: Grey & Ivy Prototype

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.35.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/crop/
  crop: ^0.5.0

# https://pub.dev/packages/mvc_application/
  mvc_application: ^7.0.0
#    path: ../../packages/mvc_application

# https://pub.dev/packages/firebase_crashlytics/
  firebase_crashlytics: ^2.0.0

# https://pub.dev/packages/firebase_auth/
#  firebase_auth: ^1.0.0
#  flutter_signin_button: ^2.0.0
#  google_sign_in: ^5.0.0

# https://pub.dev/packages/dbutils
  dbutils: ^3.0.0
#    path: ../../packages/dbutils

# https://pub.dev/packages/flutter_screenutil/
  flutter_screenutil: ^5.0.0

# https://pub.dev/packages/auto_size_text/
  auto_size_text: ^2.0.0

# https://pub.dev/packages/cached_network_image/
#  cached_network_image: ^3.0.0

## https://pub.dev/packages/scrollytell
#  scrollytell: ^1.0.0
#
## https://pub.dev/packages/photo_gallery
#  photo_gallery: ^0.4.0

#  transparent_image: ^2.0.0

#  permission_handler: ^6.0.0

#  video_player: ^2.0.0

#
#  dio: ^2.0.0

# https://pub.dev/packages/google_fonts/
  google_fonts: ^2.0.0

#  # The following adds the Cupertino Icons font to your application.
#  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.0

  # https://pub.dev/packages/remote_config
#  remote_config: ^1.0.0

# https://pub.dev/packages/image_picker/
  image_picker: 0.7.4

  # https://pub.flutter-io.cn/packages/image_size_getter/
  image_size_getter: ^1.0.0

  # https://pub.dev/packages/state_set/
  state_set: ^3.0.0
#    ../../packages/state_set

  # https://pub.dev/packages/page_view_indicators
  page_view_indicators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/
     - assets/i10n/i10n.csv

#     - assets/images/river_bend.jpg
#     - assets/images/construction_site.jpg
#     - assets/images/warehouse.jpg
#     - assets/images/warehouse_locked.jpg
#     - assets/images/city_night_locked.jpg
#     - assets/images/city_night.jpg
#
#     - assets/images/church_garbagetruck.jpg
#     - assets/images/riverbrook_pinktree.jpg
#     - assets/images/street_intersection.jpg
#     - assets/images/desert_housing.jpg
#     - assets/images/winter_cabin.jpg
#     - assets/images/city_park.jpg
#     - assets/images/country_trail.jpg
#     - assets/images/country_waterfall.jpg

     - assets/images/river_bend02.jpg
     - assets/images/construction_site02.jpg
     - assets/images/warehouse02.jpg
     - assets/images/warehouse_locked02.jpg
     - assets/images/city_night_locked02.jpg
     - assets/images/city_night02.jpg

     - assets/images/church_garbagetruck02.jpg
     - assets/images/riverbrook_pinktree02.jpg
     - assets/images/street_intersection02.jpg
     - assets/images/desert_housing02.jpg
     - assets/images/winter_cabin02.jpg
     - assets/images/city_park02.jpg
     - assets/images/country_trail02.jpg
     - assets/images/country_waterfall02.jpg

     - assets/images/abc.jpg
     - assets/images/AR.jpg
     - assets/images/movieCamera.jpg
     - assets/images/pencil.jpg
     - assets/images/picture.jpg
     - assets/images/questionMark.jpg

     - assets/google_fonts/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/google_fonts/Cabin-Regular.ttf
        - asset: assets/google_fonts/Cabin-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/google_fonts/Ubuntu-Regular.ttf
        - asset: assets/google_fonts/Ubuntu-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
